#!/bin/sh

DIR=/home/lpf/workspace/myworking/
mkdir -p ${DIR}/recipes/
mkdir -p ${DIR}/index/

rm -f ${DIR}/recipes/*
rm -f ${DIR}/index/*
rm -f ${DIR}/container.pool
rm -f ${DIR}/destor.stat
rm -f ${DIR}/manifest
